[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_22"]

[phases.install]
cmds = [
  "cd laravel_db && composer install --no-dev --optimize-autoloader --no-interaction",
  "cd laravel_db && npm install && npm run build"
]

[start]
cmd = "bash start.sh"
