FROM php:8.3-fpm

# Install system dependencies and Node.js
RUN apt-get update && apt-get install -y \
    zip unzip git curl libpq-dev libxml2-dev libonig-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring

# Set working directory
WORKDIR /var/www/html

# Copy everything into container
COPY . .

# Expose Laravel default port
EXPOSE 8000

# Start Laravel server
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]