# Gunakan PHP image
FROM php:8.3-cli

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy semua file ke container
COPY . .

# Masuk ke folder Laravel dan install dependencies
RUN cd laravel_db && composer install --no-scripts --no-interaction --optimize-autoloader

# Inisialisasi Environment (Ganti dengan cara Anda memproses file .env jika berbeda)
RUN cp laravel_db/.env.example laravel_db/.env
RUN php laravel_db/artisan key:generate

# Set permissions
RUN chmod -R 777 laravel_db/storage laravel_db/bootstrap/cache

# Expose port dinamis
EXPOSE ${PORT}

# Jalankan Laravel
CMD php laravel_db/artisan serve --host=0.0.0.0 --port=${PORT}
