# Gunakan PHP image
FROM php:8.3-cli

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy semua file ke container
COPY . .

# Masuk ke folder Laravel dan install dependencies
RUN cd laravel_db && composer install --no-scripts --no-interaction --optimize-autoloader

# Expose port dinamis
EXPOSE ${PORT}

# Jalankan Laravel
CMD php artisan serve
